version: 2
jobs:
  first-job:
    docker:
      - image: circleci/python:3.7.0
  steps:
    - checkout
    - run: echo "Hello CircleCI"
    - run: sleep 10
  second-job:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      run: echo "Second hello"
      run: sleep 15
workflows:
  version: 2
  two-jobs:
    jobs:
      - one
      - two
