version: 2
jobs:
  create_file:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - run: echo "Hello CircleCI"
      - run: mkdir test_workspace
      - run: ls > test_workspace/ls_contents.txt
      - persist_to_workspace:
          root: test_workspace
          paths:
            - ls_contents.txt
        
  print_file:
    docker:
      - image: circleci/python:3.7.0
    steps:
      - checkout
      - run:
          name: Print message
          command: echo "Retrieving from last job" 
      - attach_workspace:
          at: test_workspace
      - run:
          name: Print contents of last file
          command: cat test_workspace/ls_contents.txt
workflows:
  version: 2
  print_ls:
    jobs:
      - create_file
      - print_file:
          requires:
            - create_file
